### List employees
GET http://localhost:8081/api/employees

### Create employee
POST http://localhost:8081/api/employees
Content-Type: application/json

{
    "name": "John Doe",
    "roleId": 1
}

### Create role
POST http://localhost:8081/api/roles
Content-Type: application/json

{
    "name": "Junior developer"
}
