server:
  port: 8085

spring:
  application:
    name: mentoring-gateway
  cloud:
    gateway:
      routes:
        - id: employees
          uri: http://localhost:8081
          predicates:
            - Path=/api/employees/**
          filters:
            - AddRequestHeader=X-Request-Application, Mentoring
            - name: CircuitBreaker
              args:
                name: employeesCircuitBreaker
                fallbackUri: forward:/api/dummy-employees
        - id: roles
          uri: http://localhost:8081
          predicates:
            - Path=/api/roles/**
        - id: courses
          uri: http://localhost:8083
          predicates:
            - Path=/api/courses/**
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
